"""Add is_active attribute to User model

Revision ID: 359bf3315eb9
Revises: d877725b2920
Create Date: 2024-01-31 00:36:05.769245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '359bf3315eb9'
down_revision = 'd877725b2920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
