"""empty message

Revision ID: d2ad42745dc0
Revises: f5056df82af4
Create Date: 2024-01-25 21:05:41.788517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2ad42745dc0'
down_revision = 'f5056df82af4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_scores')
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score_value', sa.Integer(), nullable=False))
        batch_op.drop_column('score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.INTEGER(), nullable=False))
        batch_op.drop_column('score_value')

    op.create_table('_alembic_tmp_scores',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('score_value', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
